[base]
log_level = "DEBUG"
debug = false

"使用DIM功能" = true
"开启log窗口" = true
"连续失败次数" = 8 # 连续踢boss失败，超过后会重新进图

[monitor]
"检测技能就绪" = 1 # 1:猎人充能近战(x); 2:猎人闪身; 3:心影刀充能(不用检测，因为切到刀是满充能);
"开boss到射击前" =  "x_mod" # dodge_mod需要100敏捷 sword_mod需要带心影

"检测技能前切枪" = "switch_weapon"
"射击终结" =  "shot_and_finisher"
"藏头行为" = "move_and_hide"
"开boss" = "wake_up_boss"
"自杀" = "suicide_1"

"打开地图和难度选择" = "open_map_master"
"开启下一轮"= "start_next_round"
"重置进度" = "refresh_checkpoint"

