[base]
log_level = "DEBUG"
debug = false

"职业技能按键" = "0"
"未充能近战按键" = "c"
"跳隐身按键" = "x"
"终结技按键" = "v"
"埋头表情按键" = "down" # 引号里可以填写up/right/down/left
"使用DIM功能" = false
"开启log窗口" = true
"进图等待间隔" = 1.3 # 踢boss之后，点击开始下一次任务的等待时间，太大可能会进牢里，太小可能会导致没有领取奖励
"重置进度次数" = 2 # 有的时候不知道为什么会进去牢里
"连续失败次数" = 8 # 连续踢boss失败，超过后会重新进图

[monitor]
"开boss鼠标偏移" = [-42, -40]

"隐身后往左走时间" = 0 # 向左 向右决定了开局往那边走，优先向右如果都大于0的话
"隐身后往右走时间" = 1.2

"隐身后往前走时间" = 1.4

"射击黄血鼠标偏移" = [-278, 175]
"等待黄血刷新时间" = 5.908

"躲藏第一段位移镜头偏移" = [-350, 0]
"躲藏第一段位移时间" = 2.1

"躲藏第二段位移镜头偏移" = [230, 0]
"躲藏第二段位移时间" = 2

"回头看boss" = [1800, 0] # 埋头之后 回头看boss有没有传送回来

